[package]
name = "rustynet-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
rustynet-control = { path = "../rustynet-control" }
rustynetd = { path = "../rustynetd" }
ed25519-dalek = "2"
